export const notesSeed = [
  {
    nativeText: "Bonjour",
    learningText: "صباح الخير",
    pronunciation: "sbaḥ lkhir",
    noteType: "phrase",
    tags: ["salutation", "daily"],
    reviewCount: 2,
    lastReviewedAt: new Date("2025-06-20T10:00:00Z"),
    nextReviewAt: new Date("2025-06-27T10:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "Merci",
    learningText: "شكرا",
    pronunciation: "shukran",
    noteType: "phrase",
    tags: ["politeness"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-24T09:30:00Z"),
    nextReviewAt: new Date("2025-07-01T09:30:00Z"),
    ease: 3,
  },
  {
    nativeText: "Excuse-moi",
    learningText: "سمح لي",
    pronunciation: "smeh liya",
    noteType: "phrase",
    tags: ["politeness"],
    reviewCount: 3,
    lastReviewedAt: new Date("2025-06-22T14:00:00Z"),
    nextReviewAt: new Date("2025-06-29T14:00:00Z"),
    ease: 5,
  },
  {
    nativeText: "Comment ça va ?",
    learningText: "كيداير؟",
    pronunciation: "kidayr?",
    noteType: "phrase",
    tags: ["greeting", "question"],
    reviewCount: 0,
    lastReviewedAt: null,
    nextReviewAt: null,
    ease: 2,
  },
  {
    nativeText: "Je ne comprends pas",
    learningText: "مافهمتش",
    pronunciation: "ma fhmtch",
    noteType: "phrase",
    tags: ["problem", "expression"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-25T18:00:00Z"),
    nextReviewAt: new Date("2025-07-02T18:00:00Z"),
    ease: 3,
  },
  {
    nativeText: "Oui",
    learningText: "إييه",
    pronunciation: "iyyah",
    noteType: "word",
    tags: ["basic"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-23T12:00:00Z"),
    nextReviewAt: new Date("2025-06-30T12:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "Non",
    learningText: "لا",
    pronunciation: "la",
    noteType: "word",
    tags: ["basic"],
    reviewCount: 2,
    lastReviewedAt: new Date("2025-06-21T08:00:00Z"),
    nextReviewAt: new Date("2025-06-28T08:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "Combien ça coûte ?",
    learningText: "بشحال هادي؟",
    pronunciation: "bshḥal hadi?",
    noteType: "phrase",
    tags: ["shopping", "question"],
    reviewCount: 0,
    lastReviewedAt: null,
    nextReviewAt: null,
    ease: 2,
  },
  {
    nativeText: "Je t’aime",
    learningText: "كنبغيك",
    pronunciation: "kanbghik",
    noteType: "phrase",
    tags: ["love", "emotion"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-26T19:00:00Z"),
    nextReviewAt: new Date("2025-07-03T19:00:00Z"),
    ease: 5,
  },
  {
    nativeText: "Fais attention",
    learningText: "رد البال",
    pronunciation: "rdd lbal",
    noteType: "phrase",
    tags: ["warning", "safety"],
    reviewCount: 2,
    lastReviewedAt: new Date("2025-06-23T07:00:00Z"),
    nextReviewAt: new Date("2025-06-30T07:00:00Z"),
    ease: 3,
  },
  {
    nativeText: "Bienvenue",
    learningText: "مرحبا",
    pronunciation: "marḥba",
    noteType: "phrase",
    tags: ["hospitality"],
    reviewCount: 0,
    lastReviewedAt: null,
    nextReviewAt: null,
    ease: 2,
  },
  {
    nativeText: "Qu’est-ce que c’est ?",
    learningText: "شنو هادا؟",
    pronunciation: "shnu hada?",
    noteType: "phrase",
    tags: ["question", "learning"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-26T15:00:00Z"),
    nextReviewAt: new Date("2025-07-03T15:00:00Z"),
    ease: 3,
  },
];
