export const notesSeed = [
  {
    nativeText: "Bonjour",
    learningText: "صباح الخير",
    pronunciation: "sbaḥ lkhir",
    noteType: "phrase",
    tags: ["salutation", "daily"],
    reviewCount: 2,
    lastReviewedAt: new Date("2025-06-20T10:00:00Z"),
    nextReviewAt: new Date("2025-06-27T10:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "Merci",
    learningText: "شكرا",
    pronunciation: "shukran",
    noteType: "word",
    tags: ["politesse"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-22T12:00:00Z"),
    nextReviewAt: new Date("2025-06-26T12:00:00Z"),
    ease: 3,
  },
  {
    nativeText: "Comment ça va ?",
    learningText: "كيداير ؟",
    pronunciation: "kidāyr",
    noteType: "phrase",
    tags: ["salutation", "question"],
    reviewCount: 0,
  },
  {
    nativeText: "J'ai faim",
    learningText: "جوعان",
    pronunciation: "jūʿān",
    noteType: "expression",
    tags: ["besoins", "nourriture"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-21T08:00:00Z"),
    nextReviewAt: new Date("2025-06-25T08:00:00Z"),
    ease: 2,
  },
  {
    nativeText: "Où est la gare ?",
    learningText: "فين هي المحطة ؟",
    pronunciation: "fīn hī lmaḥaṭṭa",
    noteType: "phrase",
    tags: ["transport", "question"],
    reviewCount: 0,
  },
  {
    nativeText: "Je suis fatigué",
    learningText: "عييت",
    pronunciation: "ʿiyyīt",
    noteType: "phrase",
    tags: ["santé", "quotidien"],
    reviewCount: 3,
    lastReviewedAt: new Date("2025-06-24T09:00:00Z"),
    nextReviewAt: new Date("2025-07-01T09:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "Eau",
    learningText: "الماء",
    pronunciation: "l-māʔ",
    noteType: "word",
    tags: ["nourriture", "essentiel"],
    reviewCount: 0,
  },
  {
    nativeText: "Combien ça coûte ?",
    learningText: "بشحال هادي ؟",
    pronunciation: "bshḥāl hādī",
    noteType: "phrase",
    tags: ["achat", "argent"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-23T11:00:00Z"),
    nextReviewAt: new Date("2025-06-29T11:00:00Z"),
    ease: 3,
  },
  {
    nativeText: "Je ne comprends pas",
    learningText: "ما فهمتش",
    pronunciation: "mā fhmtsh",
    noteType: "phrase",
    tags: ["conversation", "base"],
    reviewCount: 2,
    lastReviewedAt: new Date("2025-06-22T14:00:00Z"),
    nextReviewAt: new Date("2025-06-30T14:00:00Z"),
    ease: 4,
  },
  {
    nativeText: "À bientôt",
    learningText: "نتلاقاو",
    pronunciation: "ntlāqāw",
    noteType: "phrase",
    tags: ["salutation"],
    reviewCount: 1,
    lastReviewedAt: new Date("2025-06-20T15:00:00Z"),
    nextReviewAt: new Date("2025-06-25T15:00:00Z"),
    ease: 2,
  },
];
